# Generated by Django 5.1.6 on 2025-02-25 14:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-bookmark', help_text='Bootstrap icon class name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sermon Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SermonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(null=True, upload_to='sermon_series/thumbnails/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sermon Series',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SermonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sermon_notes', models.FileField(blank=True, null=True, upload_to='sermon_notes/')),
                ('study_materials', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('key_points', models.TextField(blank=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('scripture_reference', models.CharField(max_length=200)),
                ('date_preached', models.DateField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='sermons/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])])),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])])),
                ('presentation_slides', models.FileField(blank=True, null=True, upload_to='sermons/slides/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'pptx'])])),
                ('thumbnail', models.ImageField(null=True, upload_to='sermons/thumbnails/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('allow_comments', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sermons', to='school.sermonseries')),
                ('tags', models.ManyToManyField(blank=True, to='school.sermontag')),
            ],
            options={
                'ordering': ['-date_preached'],
            },
        ),
        migrations.CreateModel(
            name='SermonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='school.sermoncomment')),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sermon_comments', to='school.sermon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SermonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('preacher', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('scripture_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('SU', 'Sunday Service'), ('MI', 'Midweek Service'), ('RE', 'Revival'), ('CO', 'Conference'), ('YO', 'Youth Service'), ('OT', 'Other')], default='SU', max_length=2)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('main_points', models.JSONField(default=list)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('key_verses', models.TextField(blank=True, null=True)),
                ('practical_applications', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('audio_recording', models.FileField(blank=True, upload_to='sermon_audio/')),
                ('presentation_file', models.FileField(blank=True, upload_to='sermon_presentations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='school_serm_date_ac2c7d_idx'), models.Index(fields=['category'], name='school_serm_categor_123487_idx')],
            },
        ),
    ]
