# Generated by Django 5.1.6 on 2025-02-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_sermoncategory_sermonseries_sermontag_sermon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
