# Generated by Django 5.1.6 on 2025-02-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_sermon_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MATH', 'Mathematics'), ('SCI', 'Science'), ('HIST', 'History'), ('LANG', 'Languages'), ('COMP', 'Computer Science'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('video_file', models.FileField(upload_to='educational_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='educational_thumbnails/')),
                ('study_materials', models.FileField(blank=True, null=True, upload_to='study_materials/')),
                ('worksheet', models.FileField(blank=True, null=True, upload_to='worksheets/')),
                ('instructor', models.CharField(max_length=100)),
                ('duration', models.DurationField(help_text='Duration of the video (HH:MM:SS)')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
