# Generated by Django 5.1.6 on 2025-02-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_educationalvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalvideo',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the video (HH:MM:SS)', null=True),
        ),
    ]
