# Generated by Django 5.1.6 on 2025-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_educationalvideo_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalvideo',
            name='grade_level',
            field=models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('NUR', 'Nursery'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8')], default='NURSERY', max_length=3),
        ),
    ]
