# Generated by Django 5.1.6 on 2025-02-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, to='school.course'),
        ),
    ]
