# Generated by Django 5.1.6 on 2025-02-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_teacher_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade_level', 'name']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('NUR', 'Nursery'), ('G1', 'Grade 1'), ('G2', 'Grade 2'), ('G3', 'Grade 3'), ('G4', 'Grade 4'), ('G5', 'Grade 5'), ('G6', 'Grade 6'), ('G7', 'Grade 7'), ('G8', 'Grade 8')], default='NUR', help_text='Grade level for this subject', max_length=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Subject syllabus document', null=True, upload_to='subject_syllabi/'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to='school.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Subject cover image', null=True, upload_to='subject_thumbnails/'),
        ),
    ]
